#!/bin/bash
if [ "x$COVERAGE" == "xyes" ]; then
  pip install --user gcovr
  pip install --user cpp-coveralls
else
  echo "no dependencies to install"
fi

if [ "x$AUTOTOOLS" == "xyes" ]; then
  sudo add-apt-repository -y ppa:rbose-debianizer/automake &> /dev/null
  sudo apt-get -qq update
  sudo apt-get -qq install automake
  AUTOTOOLS=yes
fi
